services:
    problematic.acl_manager:
        class: Problematic\AclManagerBundle\Domain\AclManager
        arguments:
            aclProvider: "@security.acl.provider"
            securityContext: "@security.context"
