services:
    problematic.acl_manager:
        class: Problematic\AclManagerBundle\Acl\AclManager
        arguments:
            securityContext: "@security.context"
            aclProvider: "@security.acl.provider"
